# Generated by Django 5.0.6 on 2024-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Class', models.CharField(default='', max_length=30)),
                ('Section', models.CharField(default='', max_length=30)),
                ('Rollno', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
